server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(webp|jpg|jpeg|png|gif|css|js|woff2|ico)$ {
        expires 1M;               # Le dice al navegador que expire en 1 mes
        add_header Cache-Control "public, no-transform"; # Permite a Cloudflare guardar el archivo abiertamente
        access_log off;           # Desactiva el log para no saturar tu disco con peticiones de imágenes
    }
}